spring:
  datasource:
    url: jdbc:mysql://192.168.0.196:3306/db_data_center?useUnicode=true&characterEncoding=UTF8
    username: root
    password: znsb2016
    driver-class-name: com.mysql.jdbc.Driver
  aop:
    auto: true
#    使用dbcp2
#    dbcp2:
#      initial-size: 5
#      max-idle: 8
#      min-idle: 1
#      validation-query: select 1
#      max-wait-millis: 10000
#    指定使用那个连接池，默认使用tomcate-jdbc连接池
#    type:
