
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/data_etl
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
#  开发
#    cache: false
#  data:
#    jpa:
#      repositories:
#        enabled: true
#  jpa:
#    generate-ddl: true
server:
  port: 12200
